import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Navigation } from "@/src/components/molecules/Navigation";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="min-h-screen bg-gray-50">
          <div className="mx-auto flex min-h-screen max-w-7xl gap-8 px-6 py-10">
            <Navigation />
            <main className="flex-1 overflow-hidden rounded-3xl bg-white shadow-sm ring-1 ring-gray-100">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
